# Generated by Django 3.2.6 on 2023-02-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\123\\Desktop\\LivelyHead\\LivelyHead\\media'),
        ),
    ]
