# Generated by Django 3.2.5 on 2023-03-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\DreamingHead\\OneDrive\\Рабочий стол\\LivelyHead — копия\\LivelyHead\\media'),
        ),
    ]
