# Generated by Django 3.2.5 on 2023-04-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\DreamingHead\\OneDrive\\Рабочий стол\\LivelyHead\\media'),
        ),
    ]
