# Generated by Django 3.2.5 on 2023-03-14 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Second_Name', models.CharField(max_length=20)),
                ('Photo', models.ImageField(upload_to='')),
                ('About_yourself', models.TextField(max_length=250)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Skill_Percent', models.IntegerField()),
                ('Skill_description', models.TextField()),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Anketi.person')),
            ],
        ),
    ]
