# Generated by Django 3.2.5 on 2023-03-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anketi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='Skill_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='Skill_Percent',
            new_name='percent',
        ),
    ]
